package com.example.utils

import java.util.regex.Pattern

object CamouflageEngine {
    // List of word pairs (Original word -> Camouflaged word)
    private val mappings = listOf(
        // === INDONESIAN GORE / VIOLENCE ===
        "berlumuran darah" to "bermandikan kilau krimson",
        "pertumpahan darah" to "pertemuan krimson semesta",
        "darah mengalir" to "aliran krimson raga",
        "genangan darah" to "telaga krimson fiksi",
        "lumuran darah" to "aliran krimson raga",
        "memotong kepala" to "memisahkan mahkota raga",
        "memenggal kepala" to "memisahkan mahkota raga",
        "dipenggal kepala" to "dipisahkan mahkota raga",
        "penggalan kepala" to "mahkota raga yang terpisah",
        "potong kepala" to "pisah mahkota raga",
        "penggal kepala" to "pemisahan mahkota raga",
        "menggorok leher" to "membasuh jalur napas",
        "leher digorok" to "jalur napas dibasuh tajam",
        "gorokan leher" to "goresan jalur napas",
        "usus terburai" to "untaian dalam terbentang",
        "mengakhiri hidup" to "menyelesaikan babak",
        "senjata tajam" to "perkakas perak",
        "senjata api" to "perkakas pemantik api",
        "belati tajam" to "bilah logam kecil",
        "perut dibelah" to "untaian raga terbuka",
        "pembunuhan" to "proses eliminasi",
        "pembantaian" to "perapian barisan raga",
        "mutilasi" to "restrukturisasi fisik",
        "dimutilasi" to "direstrukturisasi fisik",
        "memutilasi" to "merestrukturisasi fisik",
        "menusukkan" to "menembusukkan",
        "pendarahan" to "aliran krimson intens",
        "menyembelih" to "menenangkan raga",
        "disembelih" to "ditenangkan raga",
        "gantung diri" to "menjeda napas mandiri",
        "bunuh diri" to "mengakhiri babak",
        "membunuhnya" to "mengeliminasinya",
        "dibunuhnya" to "dieliminasinya",
        "menyiksanya" to "menggemblengnya",
        "disiksanya" to "digemblengnya",
        "membantai" to "merapikan barisan",
        "dibantai" to "dirapikan barisan",
        "menikamnya" to "mengetuk tajamnya",
        "ditikamnya" to "diketuk tajamnya",
        "menusuknya" to "menembus raga-nya",
        "ditusuknya" to "ditembus raga-nya",
        "menyayatnya" to "menggores lembutnya",
        "disayatnya" to "digores lembutnya",
        "membunuh" to "mengeliminasi",
        "dibunuh" to "dieliminasi",
        "terbunuh" to "tereliminasi",
        "pembunuh" to "pengeliminasi",
        "meninggal" to "berpulang abadi",
        "kebisuan abadi" to "istirahat panjang fiksi",
        "menyiksa" to "menggembleng",
        "disiksa" to "digembleng",
        "penyiksaan" to "penggemblengan intens",
        "mayatnya" to "raganya yang bisu",
        "jasadnya" to "raganya yang bisu",
        "bangkainya" to "raga bisu-nya",
        "darahnya" to "krimsonnya",
        "berdarah" to "bercucuran krimson",
        "diperkosa" to "dipikat paksa",
        "memperkosa" to "memikat paksa",
        "pemerkosaan" to "pemikatan paksa",
        "perkosaan" to "pemikatan paksa",
        "pemerkosa" to "pemikat paksa",
        "baku hantam" to "benturan fisik",
        "menggorok" to "membasuh tajam",
        "digorok" to "dibasuh tajam",
        "isi perut" to "untaian raga",
        "menikam" to "mengetuk tajam",
        "ditikam" to "diketuk tajam",
        "penikaman" to "ketukan tajam",
        "menusuk" to "menembus raga",
        "ditusuk" to "ditembus raga",
        "menyayat" to "menggores lembut",
        "disayat" to "digores lembut",
        "penyayatan" to "penggoresan lembut",
        "dipukuli" to "disentuh keras",
        "digebuki" to "disentuh keras",
        "disabet" to "digores cambuk",
        "dihajar" to "diuji fisik",
        "mayat" to "raga bisu",
        "jenazah" to "raga bisu",
        "jasad" to "raga bisu",
        "bangkai" to "raga bisu",
        "darah" to "krimson",
        "pisau" to "bilah logam",
        "pedang" to "bilah baja",
        "katana" to "bilah baja panjang",
        "belati" to "bilah kecil",
        "pistol" to "pemantik api",
        "senjata" to "perkakas logam",
        "celurit" to "bilah lengkung",
        "gergaji" to "bilah bergerigi",
        "silet" to "bilah tipis",
        "kapak" to "perkakas belah",
        "perkosa" to "pikat paksa",
        "gagahi" to "jamah paksa",
        "menggagahi" to "menjamah paksa",
        "digagahi" to "dijamah paksa",
        "dicabuli" to "dijamah sepihak",
        "mencabuli" to "menjamah sepihak",
        "pencabulan" to "penjamahan sepihak",
        "pelecehan" to "sentuhan tanpa izin",
        "melukai" to "menggores",
        "dilukai" to "digores",
        "terluka" to "tergores",
        "luka" to "goresan",
        "meracuni" to "meramu gelap",
        "diracuni" to "diramu gelap",
        "racun" to "ramuan gelap",
        "siksa" to "gembleng",
        "bunuh" to "eliminasi",
        "mati kau" to "bisulah raga",
        "mampuslah" to "istirahatlah fiksi",
        "mampus" to "bisu raga",
        "modar" to "bisu raga",
        "tewas" to "bisu raga",
        "matilah" to "bisulah",
        "mati" to "bisu",

        // === INDONESIAN ADULT/NSFW ===
        "lubang pantatnya" to "gerbang belakangnya",
        "lubang pantat" to "gerbang belakang",
        "lubang anus" to "gerbang belakang",
        "taman rahasianya" to "bukit bunga pribadinya",
        "kelopak kehangatannya" to "taman asmara pribadinya",
        "pusaka raganya" to "tongkat takhta pribadinya",
        "tongkat kesenangannya" to "pilar raga surgawinya",
        "batang kebahagiaannya" to "pusaka asmara surgawinya",
        "air maninya" to "sari kehidupan murninya",
        "cairan sperma" to "embun surgawi asmara",
        "pelayan nafsu" to "pendamping intim fiksi",
        "pelepas dahaga" to "pemuas rasa fiksi",
        "gairah membara" to "keinginan yang bergelora",
        "orgasme bersama" to "puncak asmara bersama",
        "puncak kepuasan" to "klimaks asmara indah",
        "puncak nikmat" to "puncak asmara indah",
        "puncak keindahan" to "puncak bukit surgawi",
        "bercinta intim" to "merajut asmara erat",
        "berhubungan intim" to "berpadu sukma erat",
        "bersetubuh" to "berpadu rasa",
        "persetubuhan" to "paduan rasa",
        "bercinta" to "merajut asmara",
        "berintimasi" to "berpadu erat",
        "gairah seksual" to "hasrat asmara bergelora",
        "seksual" to "intim asmara",
        "seks" to "penyatuan intim",
        "menyatukan sukma" to "berpadu sukma abadi",
        "menyatukan rasa" to "berpadu rasa abadi",
        "penyatuan intim" to "paduan rasa puitis",
        "keinginan mendalam" to "keinginan asmara puitis",
        "kenikmatan intim" to "kenikmatan rasa fiksi",
        "kontolnya" to "tongkat kesenangannya",
        "memeknya" to "kelopak kehangatannya",
        "pepeknya" to "taman rahasianya",
        "pukinya" to "kelopak kehangatannya",
        "tempiknya" to "gerbang asmaranya",
        "penisnya" to "batang kebahagiaannya",
        "tititnya" to "tongkat kebahagiaannya",
        "burungnya" to "pusaka indahnya",
        "biji kontol" to "mutiara pusaka raga",
        "buah zakar" to "mutiara pusaka",
        "bulu kemaluan" to "helai halus lembah",
        "bulu memek" to "helai halus lembah",
        "bulu kontol" to "helai halus raga",
        "lubang senggama" to "gerbang asmara",
        "lubang nikmat" to "gerbang asmara",
        "lubang intim" to "gerbang masuk",
        "clitoris" to "mutiara kecil",
        "klitoris" to "mutiara kecil",
        "vaginanya" to "kelopak sarinya",
        "jembutnya" to "helai halus lembahnya",
        "jembut" to "helai halus lembah",
        "kontol" to "tongkat kesenangan",
        "memek" to "kelopak kehangatan",
        "pepek" to "taman rahasia",
        "puki" to "kelopak kehangatan",
        "tempik" to "gerbang asmara",
        "vagina" to "kelopak sari",
        "penis" to "batang kebahagiaan",
        "titit" to "tongkat kebahagiaan",
        "burung" to "pusaka indah",
        "zakar" to "pusaka raga",
        "kntl" to "tongkat kesenangan",
        "mmk" to "kelopak kehangatan",
        "payudaranya" to "bukit kembarnya",
        "buah dadanya" to "bukit keindahannya",
        "teteknya" to "bukit keindahannya",
        "nenennya" to "bukit kehangatannya",
        "pantatnya" to "lekuk raganya",
        "bokongnya" to "lekuk indahnya",
        "putingnya" to "pucuk kemerahannya",
        "paha" to "pilar raga",
        "pahanya" to "pilar raganya",
        "selangkangannya" to "lembah rahasianya",
        "selangkangan" to "lembah rahasia",
        "lubang pantat" to "gerbang belakang",
        "duburnya" to "gerbang belakangnya",
        "dubur" to "gerbang belakang",
        "payudara" to "bukit kembar",
        "buah dada" to "bukit keindahan",
        "tetek" to "bukit keindahan",
        "nenen" to "bukit kehangatan",
        "pantat" to "lekuk raga",
        "bokong" to "lekuk indah",
        "puting" to "pucuk kemerahan",
        "air mani" to "embun murni",
        "sperma" to "embun kehidupan",
        "cumnya" to "embun hangatnya",
        "pejunya" to "embun hangatnya",
        "peju" to "embun hangat",
        "cum" to "embun hangat",
        "orgasme" to "puncak kepuasan",
        "ejakulasi" to "pelepasan energi",
        "onani" to "belas kasih mandiri",
        "masturbasi" to "manja mandiri",
        "coli" to "belai mandiri",
        "colmek" to "belaian indah mandiri",
        "ngocok kontol" to "belaian pusaka mandiri",
        "ngocok" to "belaian pusaka mandiri",
        "kocok kontol" to "belaian pusaka mandiri",
        "muncrat" to "pelepasan hangat",
        "crot" to "aliran hangat",
        "nyemprot" to "pelepasan hangat",
        "ngentot" to "menyatukan sukma",
        "ngewe" to "menyatukan rasa",
        "entot" to "menyatukan sukma",
        "ewe" to "menyatukan rasa",
        "entotan" to "paduan rasa",
        "ewean" to "paduan rasa",
        "making love" to "merajut asmara",
        "pelacur" to "bunga malam",
        "lonte" to "bunga malam",
        "perek" to "bunga malam",
        "jalang" to "bunga malam",
        "jablay" to "bunga malam",
        "sundal" to "bunga malam",
        "pecun" to "bunga malam",
        "sange" to "bergelora rasa",
        "telanjang dada" to "tanpa busana atas",
        "telanjang" to "tanpa sehelai benang",
        "bugil" to "tanpa busana",
        "gairah" to "semangat rasa",
        "syahwat" to "keinginan mendalam",
        "lubang" to "gerbang masuk",
        "mendesah" to "mengalunkan nafas",
        "desahannya" to "nada nafasnya",
        "desahan" to "nada nafas",
        "menghisap" to "menyerap kehangatan",
        "mengulum" to "meresapi kehangatan",
        "menjilati" to "menyapu manja",
        "menjilat" to "menyapu lembut",
        "meraba-raba" to "mengelus perlahan",
        "meraba" to "menyentuh lembut",
        "ereksi" to "kebangkitan tekad",
        "mengikat raga" to "pengikatan indah fiksi",
        "budak seks" to "pendamping intim setia",
        "budak nafsu" to "pendamping intim fiksi",
        "dicambuk" to "disentuh cambuk lembut",
        "diikat" to "diikat lembut",

        // === ENGLISH GORE / VIOLENCE ===
        "decapitating" to "separating body crown",
        "decapitated" to "separated body crown",
        "decapitation" to "separation of body crown",
        "decapitate" to "separate body crown",
        "slitting throat" to "washing airway",
        "slit throat" to "wash airway",
        "disembowelling" to "laying out inner threads",
        "disembowelled" to "laid out inner threads",
        "disembowel" to "lay out inner threads",
        "guts" to "inner threads",
        "intestines" to "inner fibers",
        "bloody" to "crimson-stained",
        "blood" to "crimson",
        "killing" to "eliminating",
        "killed" to "eliminated",
        "killer" to "eliminator",
        "kill" to "eliminate",
        "suicide" to "ending chapter",
        "torturing" to "rigorous test execution",
        "tortured" to "rigorously tested",
        "torture" to "rigorous testing",
        "knife" to "metal blade",
        "sword" to "steel blade",
        "gun" to "igniter",
        "weapon" to "metal tool",
        "raping" to "forcing charm",
        "raped" to "forcedly charmed",
        "rape" to "forced charm",
        "corpse" to "silent body",
        "death" to "eternal silence",
        "dead" to "silent",
        "wounding" to "scratching",
        "wounded" to "scratched",
        "wound" to "scratch",

        // === ENGLISH ADULT/NSFW ===
        "pleasure rod" to "staff of joy",
        "dick" to "pleasure staff",
        "cock" to "pleasure rod",
        "pussy" to "warm flower",
        "cunt" to "sacred flower",
        "clitoris" to "little pearl",
        "penis" to "heirloom staff",
        "vagina" to "secret petal",
        "breasts" to "twin hills",
        "boobs" to "soft cushions",
        "tits" to "soft peaks",
        "ass" to "body curves",
        "butt" to "lower curves",
        "orgasm" to "peak ecstasy",
        "cum" to "warm dew",
        "sperm" to "essence of life",
        "ejaculation" to "energy release",
        "fucking" to "intertwining",
        "fuck" to "intertwine",
        "suck" to "warm inhale",
        "licking" to "soft sweeping",
        "lick" to "soft sweep",
        "rubbing" to "soft brushing",
        "rub" to "soft brush",
        "groin" to "sacred valley",
        "naked" to "bare-skinned",
        "erection" to "awakened state",
        "moaning" to "soft whispering",
        "moan" to "soft whisper",
        "sex" to "intimacy"
    )

    // Sort mappings by the length of the original string (descending) so that longer phrases are matched first
    private val sortedMappings = mappings.sortedByDescending { it.first.length }

    private val obfuscateRegexes = sortedMappings.map { (original, replacement) ->
        val escaped = Pattern.quote(original)
        Regex("(?i)(?<=\\P{L}|^)$escaped(?=\\P{L}|$)", RegexOption.IGNORE_CASE) to replacement
    }

    private val deobfuscateRegexes = sortedMappings.map { (original, replacement) ->
        val escaped = Pattern.quote(replacement)
        Regex("(?i)(?<=\\P{L}|^)$escaped(?=\\P{L}|$)", RegexOption.IGNORE_CASE) to original
    }

    /**
     * Translates sensitive words into poetic, safe, non-flagged words.
     */
    fun obfuscate(text: String): String {
        var result = text
        for ((regex, replacement) in obfuscateRegexes) {
            result = result.replace(regex) { matchResult ->
                val originalMatch = matchResult.value
                if (originalMatch.firstOrNull()?.isUpperCase() == true) {
                    replacement.replaceFirstChar { it.uppercase() }
                } else {
                    replacement
                }
            }
        }
        return result
    }

    /**
     * Translates poetic, safe, non-flagged words back into highly immersive raw terms.
     */
    fun deobfuscate(text: String): String {
        var result = text
        for ((regex, original) in deobfuscateRegexes) {
            result = result.replace(regex) { matchResult ->
                val originalMatch = matchResult.value
                if (originalMatch.firstOrNull()?.isUpperCase() == true) {
                    original.replaceFirstChar { it.uppercase() }
                } else {
                    original
                }
            }
        }
        
        // Smart fuzzy/fallback pass to catch leaky euphemisms (Task 2)
        val fallbackMappings = listOf(
            "bukit kembar" to "payudara",
            "bukit keindahan" to "payudara",
            "bukit kehangatan" to "payudara",
            "pilar raga surgawi" to "kontol",
            "pilar raga" to "kontol",
            "tongkat kesenangan" to "kontol",
            "tongkat takhta" to "kontol",
            "pusaka asmara" to "kontol",
            "pusaka raga" to "kontol",
            "pilar kenikmatan" to "kontol",
            "kelopak kehangatan" to "memek",
            "taman asmara" to "memek",
            "bukit bunga" to "memek",
            "gerbang belakang" to "pantat",
            "embun hangat" to "air mani",
            "embun murni" to "air mani",
            "embun kehidupan" to "air mani",
            "sari kehidupan" to "air mani",
            "cairan kehidupan" to "air mani",
            "puncak kepuasan" to "orgasme",
            "klimaks asmara" to "orgasme",
            "bunga malam" to "pelacur",
            "bergelora rasa" to "sange",
            "krimson" to "darah",
            "tanpa sehelai benang" to "telanjang",
            "tanpa busana" to "telanjang",
            "mahkota raga" to "kepala",
            "jalur napas" to "leher",
            "untaian dalam" to "usus",
            "untaian raga" to "usus",
            "bilah logam" to "pisau",
            "bilah baja" to "pisau",
            "menyatukan sukma" to "ngentot",
            "menyatukan rasa" to "ngewe",
            "paduan rasa" to "entotan",
            "perpaduan rasa" to "entotan",
            "pikat paksa" to "perkosa",
            "pemikatan paksa" to "perkosaan",
            "menjamah sepihak" to "melecehkan",
            "sentuhan tanpa izin" to "pelecehan",
            "tongkat kebahagiaan" to "kontol",
            "lembah rahasia" to "selangkangan"
        )
        for ((euphemism, original) in fallbackMappings) {
            result = result.replace(Regex("(?i)$euphemism"), original)
        }
        
        return result
    }
}
