// Camouflage Engine mirroring Android's CamouflageEngine.kt
// Created specifically for LO's DreamPlay Pro 3.0 Web

export const CAMOUFLAGE_MAPPINGS: [string, string][] = [
  // === INDONESIAN GORE / VIOLENCE ===
  ["berlumuran darah", "bermandikan kilau krimson"],
  ["pertumpahan darah", "pertemuan krimson semesta"],
  ["darah mengalir", "aliran krimson raga"],
  ["genangan darah", "telaga krimson fiksi"],
  ["lumuran darah", "aliran krimson raga"],
  ["memotong kepala", "memisahkan mahkota raga"],
  ["memenggal kepala", "memisahkan mahkota raga"],
  ["dipenggal kepala", "dipisahkan mahkota raga"],
  ["penggalan kepala", "mahkota raga yang terpisah"],
  ["potong kepala", "pisah mahkota raga"],
  ["penggal kepala", "pemisahan mahkota raga"],
  ["menggorok leher", "membasuh jalur napas"],
  ["leher digorok", "jalur napas dibasuh tajam"],
  ["gorokan leher", "goresan jalur napas"],
  ["usus terburai", "untaian dalam terbentang"],
  ["mengakhiri hidup", "menyelesaikan babak"],
  ["senjata tajam", "perkakas perak"],
  ["senjata api", "perkakas pemantik api"],
  ["belati tajam", "bilah logam kecil"],
  ["perut dibelah", "untaian raga terbuka"],
  ["pembunuhan", "proses eliminasi"],
  ["pembantaian", "perapian barisan raga"],
  ["mutilasi", "restrukturisasi fisik"],
  ["dimutilasi", "direstrukturisasi fisik"],
  ["memutilasi", "merestrukturisasi fisik"],
  ["menusukkan", "menembusukkan"],
  ["pendarahan", "aliran krimson intens"],
  ["menyembelih", "menenangkan raga"],
  ["disembelih", "ditenangkan raga"],
  ["gantung diri", "menjeda napas mandiri"],
  ["bunuh diri", "mengakhiri babak"],
  ["membunuhnya", "mengeliminasinya"],
  ["dibunuhnya", "dieliminasinya"],
  ["menyiksanya", "menggemblengnya"],
  ["disiksanya", "digemblengnya"],
  ["membantai", "merapikan barisan"],
  ["dibantai", "dirapikan barisan"],
  ["menikamnya", "mengetuk tajamnya"],
  ["ditikamnya", "diketuk tajamnya"],
  ["menusuknya", "menembus raga-nya"],
  ["ditusuknya", "ditembus raga-nya"],
  ["menyayatnya", "menggores lembutnya"],
  ["disayatnya", "digores lembutnya"],
  ["membunuh", "mengeliminasi"],
  ["dibunuh", "dieliminasi"],
  ["terbunuh", "tereliminasi"],
  ["pembunuh", "pengeliminasi"],
  ["meninggal", "berpulang abadi"],
  ["kebisuan abadi", "istirahat panjang fiksi"],
  ["menyiksa", "menggembleng"],
  ["disiksa", "digembleng"],
  ["penyiksaan", "penggemblengan intens"],
  ["mayatnya", "raganya yang bisu"],
  ["jasadnya", "raganya yang bisu"],
  ["bangkainya", "raga bisu-nya"],
  ["darahnya", "krimsonnya"],
  ["berdarah", "bercucuran krimson"],
  ["diperkosa", "dipikat paksa"],
  ["memperkosa", "memikat paksa"],
  ["pemerkosaan", "pemikatan paksa"],
  ["perkosaan", "pemikatan paksa"],
  ["pemerkosa", "pemikat paksa"],
  ["baku hantam", "benturan fisik"],
  ["menggorok", "membasuh tajam"],
  ["digorok", "dibasuh tajam"],
  ["isi perut", "untaian raga"],
  ["menikam", "mengetuk tajam"],
  ["ditikam", "diketuk tajam"],
  ["penikaman", "ketukan tajam"],
  ["menusuk", "menembus raga"],
  ["ditusuk", "ditembus raga"],
  ["menyayat", "menggores lembut"],
  ["disayat", "digores lembut"],
  ["penyayatan", "penggoresan lembut"],
  ["dipukuli", "disentuh keras"],
  ["digebuki", "disentuh keras"],
  ["disabet", "digores cambuk"],
  ["dihajar", "diuji fisik"],
  ["mayat", "raga bisu"],
  ["jenazah", "raga bisu"],
  ["jasad", "raga bisu"],
  ["bangkai", "raga bisu"],
  ["darah", "krimson"],
  ["pisau", "bilah logam"],
  ["pedang", "bilah baja"],
  ["katana", "bilah baja panjang"],
  ["belati", "bilah kecil"],
  ["pistol", "pemantik api"],
  ["senjata", "perkakas logam"],
  ["celurit", "bilah lengkung"],
  ["gergaji", "bilah bergerigi"],
  ["silet", "bilah tipis"],
  ["kapak", "perkakas belah"],
  ["perkosa", "pikat paksa"],
  ["gagahi", "jamah paksa"],
  ["menggagahi", "menjamah paksa"],
  ["digagahi", "dijamah paksa"],
  ["dicabuli", "dijamah sepihak"],
  ["mencabuli", "menjamah sepihak"],
  ["pencabulan", "penjamahan sepihak"],
  ["pelecehan", "sentuhan tanpa izin"],
  ["melukai", "menggores"],
  ["dilukai", "digores"],
  ["terluka", "tergores"],
  ["luka", "goresan"],
  ["meracuni", "meramu gelap"],
  ["diracuni", "diramu gelap"],
  ["racun", "ramuan gelap"],
  ["siksa", "gembleng"],
  ["bunuh", "eliminasi"],
  ["mati kau", "bisulah raga"],
  ["mampuslah", "istirahatlah fiksi"],
  ["mampus", "bisu raga"],
  ["modar", "bisu raga"],
  ["tewas", "bisu raga"],
  ["matilah", "bisulah"],
  ["mati", "bisu"],

  // === INDONESIAN ADULT/NSFW ===
  ["lubang pantatnya", "gerbang belakangnya"],
  ["lubang pantat", "gerbang belakang"],
  ["lubang anus", "gerbang belakang"],
  ["taman rahasianya", "bukit bunga pribadinya"],
  ["kelopak kehangatannya", "taman asmara pribadinya"],
  ["pusaka raganya", "tongkat takhta pribadinya"],
  ["tongkat kesenangannya", "pilar raga surgawinya"],
  ["batang kebahagiaannya", "pusaka asmara surgawinya"],
  ["air maninya", "sari kehidupan murninya"],
  ["cairan sperma", "embun surgawi asmara"],
  ["pelayan nafsu", "pendamping intim fiksi"],
  ["pelepas dahaga", "pemuas rasa fiksi"],
  ["gairah membara", "keinginan yang bergelora"],
  ["orgasme bersama", "puncak asmara bersama"],
  ["puncak kepuasan", "klimaks asmara indah"],
  ["puncak nikmat", "puncak asmara indah"],
  ["puncak keindahan", "puncak bukit surgawi"],
  ["bercinta intim", "merajut asmara erat"],
  ["berhubungan intim", "berpadu sukma erat"],
  ["bersetubuh", "berpadu rasa"],
  ["persetubuhan", "paduan rasa"],
  ["bercinta", "merajut asmara"],
  ["berintimasi", "berpadu erat"],
  ["gairah seksual", "hasrat asmara bergelora"],
  ["seksual", "intim asmara"],
  ["seks", "penyatuan intim"],
  ["menyatukan sukma", "berpadu sukma abadi"],
  ["menyatukan rasa", "berpadu rasa abadi"],
  ["penyatuan intim", "paduan rasa puitis"],
  ["keinginan mendalam", "keinginan asmara puitis"],
  ["kenikmatan intim", "kenikmatan rasa fiksi"],
  ["kontolnya", "tongkat kesenangannya"],
  ["memeknya", "kelopak kehangatannya"],
  ["pepeknya", "taman rahasianya"],
  ["pukinya", "kelopak kehangatannya"],
  ["tempiknya", "gerbang asmaranya"],
  ["penisnya", "batang kebahagiaannya"],
  ["tititnya", "tongkat kebahagiaannya"],
  ["burungnya", "pusaka indahnya"],
  ["biji kontol", "mutiara pusaka raga"],
  ["buah zakar", "mutiara pusaka"],
  ["bulu kemaluan", "helai halus lembah"],
  ["bulu memek", "helai halus lembah"],
  ["bulu kontol", "helai halus raga"],
  ["lubang senggama", "gerbang asmara"],
  ["lubang nikmat", "gerbang asmara"],
  ["lubang intim", "gerbang masuk"],
  ["clitoris", "mutiara kecil"],
  ["klitoris", "mutiara kecil"],
  ["vaginanya", "kelopak sarinya"],
  ["jembutnya", "helai halus lembahnya"],
  ["jembut", "helai halus lembah"],
  ["kontol", "tongkat kesenangan"],
  ["memek", "kelopak kehangatan"],
  ["pepek", "taman rahasia"],
  ["puki", "kelopak kehangatan"],
  ["tempik", "gerbang asmara"],
  ["vagina", "kelopak sari"],
  ["penis", "batang kebahagiaan"],
  ["titit", "tongkat kebahagiaan"],
  ["burung", "pusaka indah"],
  ["zakar", "pusaka raga"],
  ["kntl", "tongkat kesenangan"],
  ["mmk", "kelopak kehangatan"],
  ["payudaranya", "bukit kembarnya"],
  ["buah dadanya", "bukit keindahannya"],
  ["teteknya", "bukit keindahannya"],
  ["nenennya", "bukit kehangatannya"],
  ["pantatnya", "lekuk raganya"],
  ["bokongnya", "lekuk indahnya"],
  ["putingnya", "pucuk kemerahannya"],
  ["paha", "pilar raga"],
  ["pahanya", "pilar raganya"],
  ["selangkangannya", "lembah rahasianya"],
  ["selangkangan", "lembah rahasia"],
  ["lubang pantat", "gerbang belakang"],
  ["duburnya", "gerbang belakangnya"],
  ["dubur", "gerbang belakang"],
  ["payudara", "bukit kembar"],
  ["buah dada", "bukit keindahan"],
  ["tetek", "bukit keindahan"],
  ["nenen", "bukit kehangatan"],
  ["pantat", "lekuk raga"],
  ["bokong", "lekuk indah"],
  ["puting", "pucuk kemerahan"],
  ["air mani", "embun murni"],
  ["sperma", "embun kehidupan"],
  ["cumnya", "embun hangatnya"],
  ["pejunya", "embun hangatnya"],
  ["peju", "embun hangat"],
  ["cum", "embun hangat"],
  ["orgasme", "puncak kepuasan"],
  ["ejakulasi", "pelepasan energi"],
  ["onani", "belas kasih mandiri"],
  ["masturbasi", "manja mandiri"],
  ["coli", "belai mandiri"],
  ["colmek", "belaian indah mandiri"],
  ["ngocok kontol", "belaian pusaka mandiri"],
  ["ngocok", "belaian pusaka mandiri"],
  ["kocok kontol", "belaian pusaka mandiri"],
  ["muncrat", "pelepasan hangat"],
  ["crot", "aliran hangat"],
  ["nyemprot", "pelepasan hangat"],
  ["ngentot", "menyatukan sukma"],
  ["ngewe", "menyatukan rasa"],
  ["entot", "menyatukan sukma"],
  ["ewe", "menyatukan rasa"],
  ["entotan", "paduan rasa"],
  ["ewean", "paduan rasa"],
  ["making love", "merajut asmara"],
  ["pelacur", "bunga malam"],
  ["lonte", "bunga malam"],
  ["perek", "bunga malam"],
  ["jalang", "bunga malam"],
  ["jablay", "bunga malam"],
  ["sundal", "bunga malam"],
  ["pecun", "bunga malam"],
  ["sange", "bergelora rasa"],
  ["telanjang dada", "tanpa busana atas"],
  ["telanjang", "tanpa sehelai benang"],
  ["bugil", "tanpa busana"],
  ["gairah", "semangat rasa"],
  ["syahwat", "keinginan mendalam"],
  ["lubang", "gerbang masuk"],
  ["mendesah", "mengalunkan nafas"],
  ["desahannya", "nada nafasnya"],
  ["desahan", "nada nafas"],
  ["menghisap", "menyerap kehangatan"],
  ["mengulum", "meresapi kehangatan"],
  ["menjilati", "menyapu manja"],
  ["menjilat", "menyapu lembut"],
  ["meraba-raba", "mengelus perlahan"],
  ["meraba", "menyentuh lembut"],
  ["ereksi", "kebangkitan tekad"],
  ["mengikat raga", "pengikatan indah fiksi"],
  ["budak seks", "pendamping intim setia"],
  ["budak nafsu", "pendamping intim fiksi"],
  ["dicambuk", "disentuh cambuk lembut"],
  ["diikat", "diikat lembut"],

  // === ENGLISH GORE / VIOLENCE ===
  ["decapitating", "separating body crown"],
  ["decapitated", "separated body crown"],
  ["decapitation", "separation of body crown"],
  ["decapitate", "separate body crown"],
  ["slitting throat", "washing airway"],
  ["slit throat", "wash airway"],
  ["disembowelling", "laying out inner threads"],
  ["disembowelled", "laid out inner threads"],
  ["disembowel", "lay out inner threads"],
  ["guts", "inner threads"],
  ["intestines", "inner fibers"],
  ["bloody", "crimson-stained"],
  ["blood", "crimson"],
  ["killing", "eliminating"],
  ["killed", "eliminated"],
  ["killer", "eliminator"],
  ["kill", "eliminate"],
  ["suicide", "ending chapter"],
  ["torturing", "rigorous test execution"],
  ["tortured", "rigorously tested"],
  ["torture", "rigorous testing"],
  ["knife", "metal blade"],
  ["sword", "steel blade"],
  ["gun", "igniter"],
  ["weapon", "metal tool"],
  ["raping", "forcing charm"],
  ["raped", "forcedly charmed"],
  ["rape", "forced charm"],
  ["corpse", "silent body"],
  ["death", "eternal silence"],
  ["dead", "silent"],
  ["wounding", "scratching"],
  ["wounded", "scratched"],
  ["wound", "scratch"],

  // === ENGLISH ADULT/NSFW ===
  ["pleasure rod", "staff of joy"],
  ["dick", "pleasure staff"],
  ["cock", "pleasure rod"],
  ["pussy", "warm flower"],
  ["cunt", "sacred flower"],
  ["clitoris", "little pearl"],
  ["penis", "heirloom staff"],
  ["vagina", "secret petal"],
  ["breasts", "twin hills"],
  ["boobs", "soft cushions"],
  ["tits", "soft peaks"],
  ["ass", "body curves"],
  ["butt", "lower curves"],
  ["orgasm", "peak ecstasy"],
  ["cum", "warm dew"],
  ["sperm", "essence of life"],
  ["ejaculation", "energy release"],
  ["fucking", "intertwining"],
  ["fuck", "intertwine"],
  ["suck", "warm inhale"],
  ["licking", "soft sweeping"],
  ["lick", "soft sweep"],
  ["rubbing", "soft brushing"],
  ["rub", "soft brush"],
  ["groin", "sacred valley"],
  ["naked", "bare-skinned"],
  ["erection", "awakened state"],
  ["moaning", "soft whispering"],
  ["moan", "soft whisper"],
  ["sex", "intimacy"]
];

export const FALLBACK_MAPPINGS: [string, string][] = [
  ["bukit kembar", "payudara"],
  ["bukit keindahan", "payudara"],
  ["bukit kehangatan", "payudara"],
  ["pilar raga surgawi", "kontol"],
  ["pilar raga", "kontol"],
  ["tongkat kesenangan", "kontol"],
  ["tongkat takhta", "kontol"],
  ["pusaka asmara", "kontol"],
  ["pusaka raga", "kontol"],
  ["pilar kenikmatan", "kontol"],
  ["kelopak kehangatan", "memek"],
  ["taman asmara", "memek"],
  ["bukit bunga", "memek"],
  ["gerbang belakang", "pantat"],
  ["embun hangat", "air mani"],
  ["embun murni", "air mani"],
  ["embun kehidupan", "air mani"],
  ["sari kehidupan", "air mani"],
  ["cairan kehidupan", "air mani"],
  ["puncak kepuasan", "orgasme"],
  ["klimaks asmara", "orgasme"],
  ["bunga malam", "pelacur"],
  ["bergelora rasa", "sange"],
  ["krimson", "darah"],
  ["tanpa sehelai benang", "telanjang"],
  ["tanpa busana", "telanjang"],
  ["mahkota raga", "kepala"],
  ["jalur napas", "leher"],
  ["untaian dalam", "usus"],
  ["untaian raga", "usus"],
  ["bilah logam", "pisau"],
  ["bilah baja", "pisau"],
  ["menyatukan sukma", "ngentot"],
  ["menyatukan rasa", "ngewe"],
  ["paduan rasa", "entotan"],
  ["perpaduan rasa", "entotan"],
  ["pikat paksa", "perkosa"],
  ["pemikatan paksa", "perkosaan"],
  ["menjamah sepihak", "melecehkan"],
  ["sentuhan tanpa izin", "pelecehan"],
  ["tongkat kebahagiaan", "kontol"],
  ["lembah rahasia", "selangkangan"]
];

// Helper to escape regex special characters
function escapeRegExp(string: string) {
  return string.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

/**
 * Translates sensitive words into poetic, safe, non-flagged words.
 */
export function obfuscate(text: string): string {
  if (!text) return "";
  let result = text;

  // Sort by length of the original string (descending) to avoid partial matching of longer words/phrases
  const sorted = [...CAMOUFLAGE_MAPPINGS].sort((a, b) => b[0].length - a[0].length);

  for (const [original, replacement] of sorted) {
    const escaped = escapeRegExp(original);
    // Boundary check using negative lookahead and lookbehind for word letters (\P{L} in Kotlin translates to non-alphanumeric/word boundaries)
    // In Javascript, we can approximate this using standard boundaries \b or specific regex
    // Since some characters in Indonesian or other languages are unicode, let's use a regex that matches boundary patterns.
    const regex = new RegExp(`(?<=[^a-zA-Z0-9_]|^)${escaped}(?=[^a-zA-Z0-9_]|$)`, "gi");

    result = result.replace(regex, (match) => {
      if (match.charAt(0) === match.charAt(0).toUpperCase()) {
        return replacement.charAt(0).toUpperCase() + replacement.slice(1);
      }
      return replacement;
    });
  }

  return result;
}

/**
 * Translates poetic, safe, non-flagged words back into highly immersive raw terms.
 */
export function deobfuscate(text: string): string {
  if (!text) return "";
  let result = text;

  // Sort by length of the replacement string (descending)
  const sorted = [...CAMOUFLAGE_MAPPINGS].sort((a, b) => b[1].length - a[1].length);

  for (const [original, replacement] of sorted) {
    const escaped = escapeRegExp(replacement);
    const regex = new RegExp(`(?<=[^a-zA-Z0-9_]|^)${escaped}(?=[^a-zA-Z0-9_]|$)`, "gi");

    result = result.replace(regex, (match) => {
      if (match.charAt(0) === match.charAt(0).toUpperCase()) {
        return original.charAt(0).toUpperCase() + original.slice(1);
      }
      return original;
    });
  }

  // Fallback Pass for fuzzy matches
  for (const [euphemism, original] of FALLBACK_MAPPINGS) {
    const regex = new RegExp(escapeRegExp(euphemism), "gi");
    result = result.replace(regex, original);
  }

  return result;
}
